# Generated by Django 4.2.6 on 2023-11-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MastersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='master/')),
                ('text_n', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master',
                'verbose_name_plural': 'Masters',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='post/')),
                ('text', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='price/mas_1_3.jpg', upload_to='price/')),
                ('h1', models.CharField(blank=True, max_length=30, null=True)),
                ('price1', models.PositiveIntegerField(blank=True, null=True)),
                ('text1', models.TextField(blank=True, null=True)),
                ('h2', models.CharField(blank=True, max_length=30, null=True)),
                ('price2', models.PositiveIntegerField(blank=True, null=True)),
                ('text2', models.TextField(blank=True, null=True)),
                ('h3', models.CharField(blank=True, max_length=30, null=True)),
                ('price3', models.PositiveIntegerField(blank=True, null=True)),
                ('text3', models.TextField(blank=True, null=True)),
                ('h4', models.CharField(blank=True, max_length=30, null=True)),
                ('price4', models.PositiveIntegerField(blank=True, null=True)),
                ('text4', models.TextField(blank=True, null=True)),
                ('is_side', models.CharField(choices=[('r', 'Right'), ('l', 'Left')], max_length=10, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='ReportsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.CharField(max_length=13)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='SecPI1_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='secPI1/')),
                ('categories', models.CharField(choices=[('Manicure', 'Маникюр'), ('Makeup', 'Макияж'), ('Hairdresser', 'Парикмахерский')], max_length=30, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
        ),
    ]
