# Generated by Django 4.2.6 on 2023-11-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaty_salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersmodel',
            name='text_w',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
