# Generated by Django 4.2.6 on 2023-11-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaty_salon', '0002_mastersmodel_text_w'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersmodel',
            name='text_w',
            field=models.CharField(blank=True, default='lorem10', max_length=100, null=True),
        ),
    ]
