# Generated by Django 4.2.6 on 2023-11-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaty_salon', '0003_alter_mastersmodel_text_w'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='secpi1_model',
            name='categories',
        ),
    ]
