# Generated by Django 4.2.6 on 2023-11-25 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beaty_salon', '0006_bookingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beaty_salon.categories'),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beaty_salon.mastersmodel'),
        ),
    ]
